<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WindowsPowerUserMcp.Core\WindowsPowerUserMcp.Core.csproj" />
    <ProjectReference Include="..\WindowsPowerUserMcp.Security\WindowsPowerUserMcp.Security.csproj" />
    <ProjectReference Include="..\WindowsPowerUserMcp.Orchestration\WindowsPowerUserMcp.Orchestration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
    <PackageReference Include="System.Management" Version="10.0.8" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.8" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
